/*
 * JumpCloud Project API
 *
 * This is a simple API for JumpCloud Project
 *
 * API version: 1.0.0
 * Contact: petebirk@memyselfandi.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

type Statistics struct {
	Total int32 `json:"total,omitempty"`
	Average int64 `json:"average,omitempty"`
}
